# Generated by Django 5.0.2 on 2024-02-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_hobby_hobby_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='hobby_image',
            field=models.CharField(default='https://www.google.com/imgres?imgurl=https%3A%2F%2Ffjwp.s3.amazonaws.com%2Fblog%2Fwp-content%2Fuploads%2F2020%2F02%2F29113959%2Fhobby-money.png&tbnid=0COPFv_BvKsdXM&vet=12ahUKEwjikaKEiruEAxWqh-4BHdb0BHgQMygCegQIARB5..i&imgrefurl=https%3A%2F%2Fwww.flexjobs.com%2Fblog%2Fpost%2Fhobbies-turn-into-good-side-job%2F&docid=N42HQBTL9mxTaM&w=1600&h=800&q=hobbies%20image&ved=2ahUKEwjikaKEiruEAxWqh-4BHdb0BHgQMygCegQIARB5', max_length=500),
        ),
    ]
