# Generated by Django 5.0.2 on 2024-02-21 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_hobby_hobby_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='hobby_image',
            field=models.CharField(default='https://www.shutterstock.com/image-vector/hobbies-entertainment-concept-large-inscription-260nw-2136659695.jpg', max_length=500),
        ),
    ]
