# Generated by Django 5.0.2 on 2024-02-21 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_hobby_hobby_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='hobby_image',
            field=models.CharField(default='https://www.google.com/imgres?imgurl=http%3A%2F%2Fwww.campustimes.org%2Fwp-content%2Fuploads%2F2022%2F09%2FCatherine_xie_hobbies_CT-800x560-c-default.png&tbnid=TE6WuWLR3XNkVM&vet=12ahUKEwjr0dDtlruEAxXkxskDHQb2AekQMygBegQIARBP..i&imgrefurl=https%3A%2F%2Fwww.campustimes.org%2F2022%2F09%2F13%2Fthe-mysterious-case-of-the-disappearing-hobbies%2F&docid=7Gkpi1zFZLf8kM&w=800&h=560&q=hobbies%20default%20image&ved=2ahUKEwjr0dDtlruEAxXkxskDHQb2AekQMygBegQIARBP', max_length=500),
        ),
    ]
