# Generated by Django 5.0.2 on 2024-02-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_hobby_hobby_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_image',
            field=models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fdepositphotos.com%2Fphotos%2Fportfolio.html&psig=AOvVaw0sFFGGt_i295EAAF6M75Jo&ust=1708559773494000&source=images&cd=vfe&opi=89978449&ved=0CBMQjRxqFwoTCJCO8riPu4QDFQAAAAAdAAAAABAE', max_length=500),
        ),
    ]
